CONTIKI_PROJECT = reciever sender
all: $(CONTIKI_PROJECT)

PROJECT_SOURCEFILES += statistics.c

# # AES
# SOURCEDIRS += ../cryptolibs
# PROJECT_SOURCEFILES += aes.c
# SOURCEDIRS += ../cryptolibs/AES
# PROJECT_SOURCEFILES += rijndael.c

# # CLEFIA
# SOURCEDIRS += ../cryptolibs
# PROJECT_SOURCEFILES += clefia.c
# SOURCEDIRS += ../cryptolibs/clefia
# PROJECT_SOURCEFILES += clefia_ref.c

# # TEA
# SOURCEDIRS += ../cryptolibs
# PROJECT_SOURCEFILES += tea.c
# SOURCEDIRS += ../cryptolibs/tea
# PROJECT_SOURCEFILES += tea.c

# PRESENT
SOURCEDIRS += ../cryptolibs
PROJECT_SOURCEFILES += present.c

CONTIKI=/home/user/contiki-ng
include $(CONTIKI)/Makefile.include
