CONTIKI_PROJECT = reciever sender
all: $(CONTIKI_PROJECT)

SOURCEDIRS += /home/user/project/cryptolibs
PROJECT_SOURCEFILES += aes.c
SOURCEDIRS += /home/user/project/cryptolibs/AES
PROJECT_SOURCEFILES += rijndael.c

CONTIKI=/home/user/contiki-ng
include $(CONTIKI)/Makefile.include
